# Generated by Django 4.2.2 on 2023-07-03 10:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='sum',
        ),
        migrations.RemoveField(
            model_name='order_line',
            name='t_price',
        ),
        migrations.AddField(
            model_name='order_line',
            name='sum',
            field=models.FloatField(default=0, verbose_name='t_price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 13, 7, 22, 264314), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(auto_created=True, max_length=10000, primary_key=True, serialize=False),
        ),
    ]
