# Generated by Django 4.2.2 on 2023-07-03 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0005_order_total_price_order_line_sum_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 13, 42, 52, 681041), verbose_name='date'),
        ),
    ]
