# Generated by Django 4.2.2 on 2023-07-04 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0014_alter_carmodel_options_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 10, 30, 59, 384685), verbose_name='date'),
        ),
    ]
