# Generated by Django 4.2.2 on 2023-07-04 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0015_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 10, 56, 38, 862950), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='sum',
            field=models.FloatField(default=0, verbose_name='sum'),
        ),
    ]
