# Generated by Django 4.2.2 on 2023-07-04 08:51

import car_service.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0020_alter_auto_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 11, 51, 17, 443263), verbose_name='date'),
        )
    ]
