# Generated by Django 4.2.2 on 2023-07-04 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0022_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 13, 27, 35, 52388), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='sum',
            field=models.FloatField(verbose_name='sum'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
    ]
