# Generated by Django 4.2.2 on 2023-07-04 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0023_alter_order_date_alter_orderline_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 13, 28, 10, 696443), verbose_name='date'),
        ),
    ]
