# Generated by Django 4.2.2 on 2023-07-04 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0024_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 4, 16, 38, 14, 899508), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='sum',
            field=models.FloatField(default=0, verbose_name='sum'),
        ),
    ]
