# Generated by Django 4.2.2 on 2023-07-07 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0031_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 10, 55, 0, 220243), verbose_name='date'),
        ),
    ]
