# Generated by Django 4.2.2 on 2023-07-07 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0032_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 13, 38, 3, 954838), verbose_name='date'),
        ),
    ]
