# Generated by Django 4.2.2 on 2023-07-07 11:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0033_auto_description_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='car_model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientauto', to='car_service.carmodel'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 14, 20, 48, 856782), verbose_name='date'),
        ),
    ]
