# Generated by Django 4.2.2 on 2023-07-07 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0034_alter_auto_car_model_id_alter_auto_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 14, 22, 0, 240889), verbose_name='date'),
        ),
    ]
