# Generated by Django 4.2.2 on 2023-07-07 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0036_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 7, 14, 31, 3, 989116), verbose_name='date'),
        ),
    ]
