# Generated by Django 4.2.2 on 2023-07-09 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0040_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 9, 13, 58, 39, 839328), verbose_name='date'),
        ),
    ]
