# Generated by Django 4.2.2 on 2023-07-10 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0043_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 11, 42, 5, 816554), verbose_name='date'),
        ),
    ]
