# Generated by Django 4.2.2 on 2023-07-10 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0045_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 10, 13, 17, 1, 836084), verbose_name='date'),
        ),
    ]
