# Generated by Django 4.2.2 on 2023-07-12 08:21

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0051_alter_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='auto',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 11, 21, 20, 384547), verbose_name='date'),
        ),
    ]
