# Generated by Django 4.2.2 on 2023-07-12 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0052_rename_client_order_user_alter_auto_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 11, 21, 38, 876426), verbose_name='date'),
        ),
    ]
