# Generated by Django 4.2.2 on 2023-07-12 09:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0054_rename_user_order_client_user_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 12, 12, 38, 23, 335201), verbose_name='date'),
        ),
    ]
