# Generated by Django 4.2.2 on 2023-07-13 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0055_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 9, 57, 37, 680684), verbose_name='date'),
        ),
    ]
