# Generated by Django 4.2.2 on 2023-07-13 07:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0057_alter_order_date_orderreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 10, 36, 57, 538615), verbose_name='date'),
        ),
    ]
