# Generated by Django 4.2.2 on 2023-07-14 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0059_alter_order_date_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 37, 45, 928570), verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='img/no-image.jpg', upload_to='profile_pics'),
        ),
    ]
