# Generated by Django 4.2.2 on 2023-07-14 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0060_alter_order_date_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 10, 42, 21, 29569), verbose_name='date'),
        ),
    ]
