# Generated by Django 4.2.2 on 2023-07-14 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0065_alter_order_date_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='client',
            field=models.CharField(max_length=20, null=True, verbose_name='clieant'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='plate_number',
            field=models.CharField(max_length=20, null=True, verbose_name='plate_number'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='vin_code',
            field=models.CharField(max_length=20, null=True, verbose_name='VIN_code'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(max_length=20, null=True, verbose_name='make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(max_length=20, null=True, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 14, 14, 45, 34, 68154), null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Accepted'), ('p', 'In progress'), ('c', 'Completed')], default='a', help_text='Order status', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='sum',
            field=models.FloatField(default=0, null=True, verbose_name='sum'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='content',
            field=models.TextField(max_length=2000, null=True, verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='img/no-image.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(default=0, null=True, verbose_name='price'),
        ),
    ]
