# Generated by Django 4.2.2 on 2023-07-14 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0066_alter_auto_client_alter_auto_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='car_model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientauto', to='car_service.carmodel'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='client',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='clieant'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='plate_number'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='vin_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='VIN_code'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='make'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='auto_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service.auto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 14, 14, 48, 18, 423956), null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service.order'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='service_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_service.service'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='sum',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='sum'),
        ),
        migrations.AlterField(
            model_name='orderreview',
            name='content',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='review'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='img/no-image.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='price'),
        ),
    ]
