# Generated by Django 4.2.2 on 2023-07-14 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0074_alter_order_date_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 14, 15, 48, 27, 189855), null=True, verbose_name='date'),
        ),
    ]
