# Generated by Django 4.2.2 on 2023-07-14 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0075_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 14, 15, 50, 42, 574310), null=True, verbose_name='date'),
        ),
    ]
