# Generated by Django 4.2.2 on 2023-07-17 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0076_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 17, 11, 24, 7, 138581), null=True, verbose_name='date'),
        ),
    ]
