# Generated by Django 4.2.2 on 2023-07-17 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0077_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 17, 14, 33, 35, 806968), null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_back',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 17, 14, 33, 35, 806968), null=True, verbose_name='due_back'),
        ),
    ]
