# Generated by Django 4.2.2 on 2023-07-17 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0078_alter_order_date_alter_order_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 17, 14, 39, 9, 793359), null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='due_back'),
        ),
    ]
