# Generated by Django 4.2.2 on 2023-07-17 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0079_alter_order_date_alter_order_due_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 17, 16, 56, 49, 884233), null=True, verbose_name='date'),
        ),
    ]
