# Generated by Django 4.2.2 on 2023-07-18 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_service', '0082_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 18, 11, 26, 18, 843924), null=True, verbose_name='date'),
        ),
    ]
