# Generated by Django 4.2.2 on 2023-07-18 13:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_service', '0085_alter_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderline',
            name='sum',
        ),
        migrations.AlterField(
            model_name='order',
            name='client_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 18, 16, 54, 25, 467476), null=True, verbose_name='date'),
        ),
    ]
